#!/usr/bin/env bash
# In-pod driver for a PURE-IMAGE long-lived 8xB200 DEBUG pod.
#
# Unlike submit_debug_9b.sh (which builds a persistent uv venv on the PVC), this
# driver DISCARDS uv entirely and uses the container image's own Python: the
# echo-rl image already bakes the 269 runtime deps, so we just `pip install
# --no-deps -e` the four editables (SkyRL, skyrl-gym, skyrl-agent,
# mini-web-agent) straight into the system interpreter. No venv, no
# system-site-packages indirection.
#
# This script is UPLOADED with the repo and executed inside the pod via a tiny
# `--cmd` one-liner (see docker/submit_debug_pure_image.sh). Keeping the heavy
# setup here -- not inline in the Volcano job YAML -- is required: the bonete61
# API server sits behind Cloudflare, whose WAF blocks `kubectl create` POSTs
# whose body carries a big shell preamble. Moving it into an uploaded file keeps
# the create request WAF-clean.
#
# Result: after the pod reaches READY, every `kubectl exec -it <pod> -- bash`
# lands in a prepared shell (creds sourced, OPENAI key overridden, paths
# exported, cwd=SkyRL) running on the plain image Python.
#
# Required env (auto-injected by submit_job.sh):
#   PVC_MOUNT, USER_ALIAS, JOB_NAME
# Secrets (mounted as volumes):
#   /run/secrets/echo-rl-creds/cred.sh         -- BROWSERBASE_*, HF_*, gateway key
#   /run/secrets/echo-rl-openai/OPENAI_API_KEY -- working sk-proj judge key

set -e

echo "[boot] pure-image debug pod $JOB_NAME on $(hostname)"

CODE_ROOT=$PVC_MOUNT/$USER_ALIAS/code
UPLOAD_ROOT=$PVC_MOUNT/$USER_ALIAS/runs/$JOB_NAME
OUTPUT_DIR=$PVC_MOUNT/$USER_ALIAS/outputs/$JOB_NAME
ENV_ROOT=$PVC_MOUNT/$USER_ALIAS/envs/pure-image
ACTIVATE=$ENV_ROOT/env_activate.sh
READY=$ENV_ROOT/.debug_ready
rm -f "$READY"
mkdir -p "$CODE_ROOT" "$OUTPUT_DIR" "$ENV_ROOT"

echo '[boot] === copy uploaded code to stable PVC path ==='
if ! command -v rsync >/dev/null 2>&1; then
  echo '[boot] installing rsync (one-time per pod)...'
  apt-get update -qq && apt-get install -y -qq rsync
fi
rsync -a --delete --no-perms --no-owner --no-group --no-times \
    "$UPLOAD_ROOT/SkyRL/"          "$CODE_ROOT/SkyRL/"
rsync -a --delete --no-perms --no-owner --no-group --no-times \
    "$UPLOAD_ROOT/mini-web-agent/" "$CODE_ROOT/mini-web-agent/"

echo '[boot] === pip install editables into the IMAGE Python (no venv, no uv) ==='
echo "[boot] python -> $(command -v python) ; $(python -V 2>&1)"
pip install --no-deps --no-build-isolation \
    -e "$CODE_ROOT/SkyRL" \
    -e "$CODE_ROOT/SkyRL/skyrl-gym" \
    -e "$CODE_ROOT/SkyRL/skyrl-agent" \
    -e "$CODE_ROOT/mini-web-agent"
python -c "import wandb" 2>/dev/null || pip install wandb

# ------------------------------------------------------------------
# Write the sourceable activate script (fast, idempotent, re-source safe).
# Sourced by every login shell so the env is ALWAYS ready on exec.
# NOTE: no venv activation here -- the image Python is already on PATH.
# ------------------------------------------------------------------
echo "[boot] === writing $ACTIVATE ==="
cat > "$ACTIVATE" <<ACTEOF
# Auto-generated by run_debug_pure_image.sh -- prepares the pure-image echo-rl env.
source /run/secrets/echo-rl-creds/cred.sh
unset OPENAI_GATEWAY_API_KEY
# The phyagi gateway key in cred.sh is dead; use the working sk-proj key from the
# echo-rl-openai secret and route the OSW judge straight to api.openai.com.
if [ -f /run/secrets/echo-rl-openai/OPENAI_API_KEY ]; then
  export OPENAI_API_KEY="\$(cat /run/secrets/echo-rl-openai/OPENAI_API_KEY)"
  export OPENAI_GATEWAY_ENDPOINT=''
fi
export MINI_WEB_AGENT_ROOT=$CODE_ROOT/mini-web-agent
export ECHO_RL_DATA=$CODE_ROOT/mini-web-agent/data/web_agent
export OUTPUT_DIR=$OUTPUT_DIR
export TRANSFORMERS_NO_ADVISORY_WARNINGS=1
cd $CODE_ROOT/SkyRL
ACTEOF

# ------------------------------------------------------------------
# Wire the activate script into login + interactive shells so any
# 'kubectl exec' lands you in a ready environment automatically.
# ------------------------------------------------------------------
SRC_LINE="source $ACTIVATE"
GUARD='# >>> echo-rl pure-image debug env >>>'
for rc in /root/.bashrc /root/.bash_profile; do
  touch "$rc"
  if ! grep -qF "$GUARD" "$rc"; then
    printf '%s\n%s\n# <<< echo-rl pure-image debug env <<<\n' "$GUARD" "$SRC_LINE" >> "$rc"
  fi
done
if ! grep -qF '.bashrc' /root/.bash_profile 2>/dev/null; then
  printf '[ -f ~/.bashrc ] && source ~/.bashrc\n' >> /root/.bash_profile
fi

echo '[boot] === pre-flight ==='
nvidia-smi -L
python -c "import torch, vllm, transformers, wandb, echo_rl, skyrl_gym, skyrl_agent; print('torch', torch.__version__); print('vllm', vllm.__version__); print('imports OK')"

touch "$READY"
echo '[boot] ============================================================'
echo '[boot] PURE-IMAGE DEBUG ENV READY. exec into this pod for a ready shell.'
echo "[boot]   activate file: $ACTIVATE"
echo "[boot]   output dir:    $OUTPUT_DIR"
echo '[boot] ============================================================'
sleep infinity
