#!/usr/bin/env bash
# Launch a long-lived 8xB200 DEBUG pod with a fully-prepared environment.
#
# Unlike submit_interactive_8gpu.sh (which drops you into a raw shell where you
# must manually source creds + pip-install + export paths), this script:
#   * runs the full bootstrap ONCE at pod boot (creds, uv venv, editable
#     installs, env paths) -- same preamble as submit_uv_9b_easy.sh,
#   * writes a sourceable  env_activate.sh  to the PVC,
#   * wires  source env_activate.sh  into /root/.bashrc + /root/.bash_profile,
#   * then  sleep infinity  to keep the pod alive.
#
# Result: EVERY shell you `kubectl exec` into already has creds sourced, the uv
# venv active, all paths exported, and GPUs visible. You just run, e.g.:
#   python -m echo_rl.web_agent.entrypoint --config <config>.yaml
#
# This script is submitted DETACHED (no blocking TTY), so it can be driven by
# tooling. After it returns, it prints the exact `kubectl exec` command to open
# a ready interactive shell, plus how to tail the bootstrap log and clean up.
#
#   bash docker/submit_debug_9b.sh
#   GPUS=8 bash docker/submit_debug_9b.sh        # override gpu count
#
# Tear down when done:
#   kubectl -n bonete61 delete job.batch.volcano.sh/<JOB_FQN> --wait=false

set -euo pipefail

SUBMIT="${SUBMIT:-/data/t-yifeili/aifsdk/clusters/lambda/submission/submit_job.sh}"
MINI_WEB_AGENT_DIR="${MINI_WEB_AGENT_DIR:-/data/t-yifeili/mini-web-agent}"
SKYRL_DIR="${SKYRL_DIR:-/data/t-yifeili/SkyRL}"
IMAGE="${IMAGE:-aifrontiers.azurecr.io/t-yifeili/echo-rl:latest}"
GPUS="${GPUS:-8}"

for d in "$MINI_WEB_AGENT_DIR" "$SKYRL_DIR"; do
    [[ -d "$d" ]] || { echo "[error] missing $d"; exit 1; }
done

export PATH="$HOME/.krew/bin:$PATH"

# Naming for the GPU monitor dashboard (see submit_real_train_batch.sh).
export PRIORITY="${PRIORITY:-medium}"
export PRIORITY_CLASS_NAME="${PRIORITY_CLASS_NAME:-medium}"
export PROJECT_NAME="${PROJECT_NAME:-cua}"

# Forward local OPENAI_API_BACKUP_KEY into the pod as OPENAI_API_KEY_OVERRIDE so
# the om2w judge routes through api.openai.com instead of the phyagi gateway.
EXTRA_ENV_ARGS=()
if [[ -n "${OPENAI_API_BACKUP_KEY:-}" ]]; then
    EXTRA_ENV_ARGS+=(--extra-env-vars "OPENAI_API_KEY_OVERRIDE=${OPENAI_API_BACKUP_KEY}")
fi

bash "$SUBMIT" \
    --upload "$MINI_WEB_AGENT_DIR" "$SKYRL_DIR" \
    --image "$IMAGE" \
    --node 1 --gpu-per-node "$GPUS" \
    --cpu 64 --memory 512Gi --shm 64Gi \
    --secret-volume echo-rl-creds:/run/secrets/echo-rl-creds \
    "${EXTRA_ENV_ARGS[@]}" \
    --cmd "set -e
echo '[boot] debug pod \$JOB_NAME on \$(hostname)'

CODE_ROOT=\$PVC_MOUNT/\$USER_ALIAS/code
ENV_ROOT=\$PVC_MOUNT/\$USER_ALIAS/envs/echo-rl-uv
VENV=\$ENV_ROOT/.venv
UPLOAD_ROOT=\$PVC_MOUNT/\$USER_ALIAS/runs/\$JOB_NAME
OUTPUT_DIR=\$PVC_MOUNT/\$USER_ALIAS/outputs/\$JOB_NAME
ACTIVATE=\$ENV_ROOT/env_activate.sh
READY=\$ENV_ROOT/.debug_ready
rm -f \$READY
mkdir -p \$CODE_ROOT \$ENV_ROOT/bin \$OUTPUT_DIR

echo '[boot] === copy uploaded code to stable PVC path ==='
if ! command -v rsync >/dev/null 2>&1; then
  echo '[boot] installing rsync (one-time per pod)...'
  apt-get update -qq && apt-get install -y -qq rsync
fi
rsync -a --delete --no-perms --no-owner --no-group --no-times \
    \$UPLOAD_ROOT/SkyRL/          \$CODE_ROOT/SkyRL/
rsync -a --delete --no-perms --no-owner --no-group --no-times \
    \$UPLOAD_ROOT/mini-web-agent/ \$CODE_ROOT/mini-web-agent/

if [ ! -x \$ENV_ROOT/bin/uv ]; then
  echo '[boot] === install uv ==='
  curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=\$ENV_ROOT/bin INSTALLER_NO_MODIFY_PATH=1 sh
fi
export PATH=\$ENV_ROOT/bin:\$PATH

if [ ! -d \$VENV ]; then
  echo '[boot] === create uv venv (system-site-packages) ==='
  uv venv --system-site-packages --python \$(which python3) \$VENV
fi
source \$VENV/bin/activate

echo '[boot] === uv pip install editables (idempotent) ==='
uv pip install --no-deps \
    -e \$CODE_ROOT/SkyRL \
    -e \$CODE_ROOT/SkyRL/skyrl-gym \
    -e \$CODE_ROOT/SkyRL/skyrl-agent \
    -e \$CODE_ROOT/mini-web-agent
uv pip install wandb

# ------------------------------------------------------------------
# Write the sourceable activate script (fast, idempotent, re-source safe).
# Sourced by every login shell so the env is ALWAYS ready on exec.
# ------------------------------------------------------------------
echo '[boot] === writing \$ACTIVATE ==='
cat > \$ACTIVATE <<ACTEOF
# Auto-generated by submit_debug_9b.sh -- prepares the echo-rl debug env.
source /run/secrets/echo-rl-creds/cred.sh
unset OPENAI_GATEWAY_API_KEY
if [ -n \"\\\${OPENAI_API_KEY_OVERRIDE:-}\" ]; then
  export OPENAI_API_KEY=\"\\\${OPENAI_API_KEY_OVERRIDE}\"
  export OPENAI_GATEWAY_ENDPOINT=''
fi
export PATH=\$ENV_ROOT/bin:\\\$PATH
source \$VENV/bin/activate
export MINI_WEB_AGENT_ROOT=\$CODE_ROOT/mini-web-agent
export ECHO_RL_DATA=\$CODE_ROOT/mini-web-agent/data/web_agent
export OUTPUT_DIR=\$OUTPUT_DIR
export TRANSFORMERS_NO_ADVISORY_WARNINGS=1
cd \$CODE_ROOT/SkyRL
ACTEOF

# ------------------------------------------------------------------
# Wire the activate script into login + interactive shells so any
# 'kubectl exec' lands you in a ready environment automatically.
# ------------------------------------------------------------------
SRC_LINE=\"source \$ACTIVATE\"
GUARD='# >>> echo-rl debug env >>>'
for rc in /root/.bashrc /root/.bash_profile; do
  touch \$rc
  if ! grep -qF \"\$GUARD\" \$rc; then
    printf '%s\n%s\n# <<< echo-rl debug env <<<\n' \"\$GUARD\" \"\$SRC_LINE\" >> \$rc
  fi
done
# login shells read .bash_profile; make sure it also pulls in .bashrc
if ! grep -qF '.bashrc' /root/.bash_profile 2>/dev/null; then
  printf '[ -f ~/.bashrc ] && source ~/.bashrc\n' >> /root/.bash_profile
fi

echo '[boot] === pre-flight ==='
nvidia-smi -L
python -c \"import torch, vllm, transformers, wandb, echo_rl, skyrl_gym, skyrl_agent; print('torch', torch.__version__); print('vllm', vllm.__version__); print('imports OK')\"

touch \$READY
echo '[boot] ============================================================'
echo '[boot] DEBUG ENV READY. exec into this pod to get a prepared shell.'
echo '[boot]   activate file: '\$ACTIVATE
echo '[boot]   output dir:    '\$OUTPUT_DIR
echo '[boot] ============================================================'
sleep infinity
"
