python - <<'PY'
from pathlib import Path
import re, subprocess, os, json
p = Path('final_script.py')
text = p.read_text()
pattern = re.compile(r'''\s*log\("Open Marriott homepage"\)\n\s*await goto_with_retry\(page, "https://www\.marriott\.com/default\.mi", "Marriott homepage", attempts=2, timeout=45000\)\n\s*await click_if_visible\(page, page\.get_by_role\("button", name=re\.compile\("accept\|agree", re\.I\)\), "cookie accept button"\)\n\n\s*hv_link = page\.locator\('a\[href="https://homes-and-villas\.marriott\.com/en/collections"\]'\)\n\s*hv_count = await hv_link\.count\(\)\n\s*log\(f"Homepage title: \{await page\.title\(\)\}"\)\n\s*log\(f"Dedicated Homes & Villas entry count: \{hv_count\}"\)\n\s*if hv_count:\n\s*    try:\n\s*        await hv_link\.first\.scroll_into_view_if_needed\(timeout=5000\)\n\s*    except Exception as e:\n\s*        log\(f"Dedicated entry scroll was not completed: \{e\}"\)\n\s*    href = await hv_link\.first\.get_attribute\('href'\)\n\s*    log\(f"Dedicated Homes & Villas entry href: \{href\}"\)\n\s*else:\n\s*    log\("Dedicated Homes & Villas entry href not found on homepage during this run"\)\n\s*await page\.wait_for_timeout\(1000\)\n\s*await page\.screenshot\(path=str\(SCREENSHOTS / "final_execution_1_marriott_home_dedicated_entry\.png"\)\)\n\n\s*if hv_count:\n\s*    try:\n\s*        await hv_link\.first\.click\(timeout=5000\)\n\s*        await page\.wait_for_load_state\("domcontentloaded"\)\n\s*        await page\.wait_for_timeout\(3000\)\n\s*    except Exception as e:\n\s*        log\(f"Dedicated entry click did not navigate cleanly: \{e\}"\)\n\s*    if "homes-and-villas\.marriott\.com" not in page\.url and href:\n\s*        log\("Dedicated entry click did not leave Marriott homepage; navigating to the dedicated Homes & Villas target href discovered on Marriott\.com"\)\n\s*        await goto_with_retry\(page, href, "dedicated Homes & Villas entry target from Marriott homepage", attempts=2, timeout=45000\)\n\s*        await page\.wait_for_timeout\(2000\)\n\s*log\(f"After dedicated entry navigation URL: \{page\.url\}"\)\n\s*log\(f"Collections title: \{await page\.title\(\)\}"\)\n\s*await page\.screenshot\(path=str\(SCREENSHOTS / "final_execution_2_homes_villas_collections\.png"\)\)''', re.S)
replacement = '''        log("Open Marriott homepage")\n        href = None\n        hv_count = 0\n        for homepage_attempt in range(1, 5):\n            await goto_with_retry(page, "https://www.marriott.com/default.mi", f"Marriott homepage load cycle {homepage_attempt}", attempts=2, timeout=45000)\n            await click_if_visible(page, page.get_by_role("button", name=re.compile("accept|agree", re.I)), "cookie accept button")\n            hv_link = page.locator('a[href="https://homes-and-villas.marriott.com/en/collections"]')\n            hv_count = await hv_link.count()\n            homepage_title = await page.title()\n            log(f"Homepage cycle {homepage_attempt} title: {homepage_title}")\n            log(f"Homepage cycle {homepage_attempt} dedicated Homes & Villas entry count: {hv_count}")\n            if hv_count and homepage_title.strip():\n                try:\n                    await hv_link.first.scroll_into_view_if_needed(timeout=5000)\n                except Exception as e:\n                    log(f"Dedicated entry scroll was not completed: {e}")\n                href = await hv_link.first.get_attribute('href')\n                log(f"Dedicated Homes & Villas entry href: {href}")\n                break\n            log("Dedicated Homes & Villas entry not ready on this homepage load cycle; retrying homepage")\n            await page.wait_for_timeout(2000)\n\n        log(f"Homepage title: {await page.title()}")\n        log(f"Dedicated Homes & Villas entry count: {hv_count}")\n        if not href:\n            raise RuntimeError("Could not find dedicated Homes & Villas entry on Marriott homepage after retries")\n        await page.wait_for_timeout(1000)\n        await page.screenshot(path=str(SCREENSHOTS / "final_execution_1_marriott_home_dedicated_entry.png"))\n\n        try:\n            await hv_link.first.click(timeout=5000)\n            await page.wait_for_load_state("domcontentloaded")\n            await page.wait_for_timeout(3000)\n        except Exception as e:\n            log(f"Dedicated entry click did not navigate cleanly: {e}")\n        if "homes-and-villas.marriott.com" not in page.url:\n            log("Dedicated entry click did not leave Marriott homepage; navigating to the dedicated Homes & Villas target href discovered on Marriott.com")\n            await goto_with_retry(page, href, "dedicated Homes & Villas entry target from Marriott homepage", attempts=2, timeout=45000)\n            await page.wait_for_timeout(2000)\n        if "homes-and-villas.marriott.com" not in page.url:\n            raise RuntimeError(f"Failed to reach Homes & Villas from Marriott homepage dedicated entry; current URL: {page.url}")\n        log(f"After dedicated entry navigation URL: {page.url}")\n        log(f"Collections title: {await page.title()}")\n        await page.screenshot(path=str(SCREENSHOTS / "final_execution_2_homes_villas_collections.png"))'''
text2, n = pattern.subn(replacement, text, count=1)
if n != 1:
    raise SystemExit('failed to replace homepage block')
p.write_text(text2)
print('patched final_script.py')
subprocess.run('python final_script.py', shell=True, check=True)
run = sorted([x.name for x in Path('final_runs').glob('run_*')])[-1]
print('RUN='+run)
cmd = f'python -m self_reflection --config judge_config.json --workspace-dir "{os.getcwd()}" --output final_runs/{run}/judge_result.json'
subprocess.run(cmd, shell=True, check=True)
print(Path(f'final_runs/{run}/judge_result.json').read_text())
PY
